### ISSUE TITLE
Swarm-PINN question

### ISSUE THREAD

**Issue by mirix** [jaem-seo/pinn-optimization#1]
Hi Jaemin,

I have a completely off-topic question. This is not an issue but rather a philosophical discussion. 

1. Let's say we have an observable output (O) and a number of features (F) that we believe have an effect of the observed output. 

2. Let's say our data is a time series and we wish to carry out forecasting, this is, predicting future values of O on the basis of the past correlation patterns between O and F.

3. We suspect that some of the features are actually stimuli that trigger an unobserved swarm behaviour which, at least in part, is responsible for the outcome.

4. The swarm behaviour is not observable. So we do not know how the individual actors react to to the stimuli F. 

In such context, would it be possible and would it make sense in your opinion to use a PINN-like strategy and somehow embed a swarm algorithm in our neural network in order to optimise its forecasting performance?

Knowing that:

1. Not all features F are stimuli, some may just be information.

2. The swarm behaviour is not absolutely deterministic and does not fully account for the observable O.

3. Our hypothesis, however, is that the underlying swarm behaviour represents a substantial contribution to O.

What do you think?

Best regards,

Ed Moman

**Comment by jaem-seo** [comment]
Well, it sounds quite philosophical. I don't think I fully understood your question. Could you give me some more specific examples for O and F?

But as a general answer, a PINN-like strategy surely can be improved to find the optimum if it is embedded into a swarm algorithm. PINN does not always find the global optimum and it sometimes needs multiple agents like ensemble models. A swarm algorithm will more effectively find the optimum than a simple ensemble PINNs.

**Comment by mirix** [comment]
Thanks for your response Jaemin. What I have in mind right now is using AI for automated trading. 

The idea would be to have a web-crawler collecting "stimuli" from different sources (financial news, social media and even the deep web), transform those stimuli into some numerical form (sentiment analysis or otherwise), and then develop forecasting models using historical information. 

My hypothesis is that such stimuli should trigger swarm behaviours on large numbers of small traders. 

I would like to compare a machine learning model (neural network or otherwise) that does not take into account the potential underlying swarm behaviour with another model which has this behaviour somehow imbued to see if there is any benefit from such approach.

I sent you a connection request on LinkedIn, I am Ed Moman.
