### ISSUE TITLE
Different activations in outputs of the pendulum network

### ISSUE THREAD

**Issue by isfons** [jaem-seo/pinn-optimization#2]
Dear Jaemin,

I have tried to replicate the example of the pendulum. In the paper, you explain that two different activations are used in the output layer of the network, namely tanh and sigmoid. However, when I checked the piece of code where you define the net, it seems that only tanh was applied:
`net = dde.nn.FNN([1] + [64] * 3 + [n_output], "tanh", "Glorot normal")`

As I might have not understood either the code or the paper correctly, could you please clarify how the anlge was modeled to range between 0 and 2pi?

Thanks a lot in advance

**Comment by jaem-seo** [comment]
Hi, the detailed neural net settings are different for each task. For the pendulum task, the output layer has two parameters: angle and torque. And only the second output (torque) is clipped via tanh, in line 45 of the `pinn-optimization/data/inverting_pendulum/main.py`.

The script below does not add any activation in the output layer, so the output layer can have any values, not between 0 to 2pi.
`net = dde.nn.FNN([1] + [64] * 3 + [n_output], "tanh", "Glorot normal")`

So the angle is not limited between 0 and 2pi, as you can see some large values in Figure 5b in the paper. But the torque is limited between -torq_max and +torq_max (you can see the clipping at lines 45-46 in `pinn-optimization/data/inverting_pendulum/main.py` ).

Let me know if you have further questions. Thanks.

**Comment by isfons** [comment]
I do appreciate it that  you attended my query so fast. 

The provided answer has been absolutely helpful, as I was not aware that no activation was being applied to the output layer. 

Thank you very much 👍
